PRAGMA foreign_keys = ON;
CREATE TABLE users (id TEXT PRIMARY KEY, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE auth_sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at INTEGER NOT NULL);
CREATE INDEX auth_sessions_user ON auth_sessions(user_id);
CREATE TABLE login_attempts (key TEXT PRIMARY KEY, attempts INTEGER NOT NULL, window_start INTEGER NOT NULL);
CREATE TABLE user_settings (user_id TEXT PRIMARY KEY REFERENCES users(id), preferences TEXT NOT NULL CHECK(json_valid(preferences)));
CREATE TABLE dashboard_widgets (user_id TEXT NOT NULL REFERENCES users(id), key TEXT NOT NULL CHECK(key IN ('fitness','travel','weekly','recent')), visible INTEGER NOT NULL CHECK(visible IN(0,1)), size TEXT NOT NULL CHECK(size IN('small','medium','large')), position INTEGER NOT NULL, PRIMARY KEY(user_id,key));
CREATE TABLE data_source_versions (id TEXT PRIMARY KEY, url TEXT NOT NULL, source_commit TEXT NOT NULL, sha256 TEXT NOT NULL, license TEXT NOT NULL, record_count INTEGER NOT NULL, imported_at TEXT NOT NULL);

CREATE TABLE exercise_library (id TEXT PRIMARY KEY, name_en TEXT NOT NULL, name_zh TEXT NOT NULL, body_part TEXT NOT NULL, target TEXT NOT NULL, secondary_muscles TEXT NOT NULL CHECK(json_valid(secondary_muscles)), equipment TEXT NOT NULL, instructions_en TEXT NOT NULL CHECK(json_valid(instructions_en)), instructions_zh TEXT NOT NULL CHECK(json_valid(instructions_zh)), source_commit TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE INDEX exercise_filters ON exercise_library(body_part,target,equipment,active);
CREATE INDEX exercise_name ON exercise_library(name_en);
CREATE TABLE exercise_media (id TEXT PRIMARY KEY, exercise_id TEXT NOT NULL REFERENCES exercise_library(id), image TEXT, animation TEXT, attribution TEXT NOT NULL, license TEXT NOT NULL, approved INTEGER NOT NULL DEFAULT 0);
CREATE TABLE exercise_favorites (user_id TEXT NOT NULL REFERENCES users(id), exercise_id TEXT NOT NULL REFERENCES exercise_library(id), created_at TEXT NOT NULL, PRIMARY KEY(user_id,exercise_id));
CREATE TABLE fitness_sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), title TEXT NOT NULL, mode TEXT NOT NULL CHECK(mode IN('quick','detailed')), status TEXT NOT NULL CHECK(status IN('draft','active','completed')), body_parts TEXT NOT NULL CHECK(json_valid(body_parts)), start_at TEXT NOT NULL, end_at TEXT, timezone TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', visibility TEXT NOT NULL DEFAULT 'private' CHECK(visibility IN('private','public')), updated_at TEXT NOT NULL, CHECK(end_at IS NULL OR end_at >= start_at));
CREATE INDEX fitness_owner_date ON fitness_sessions(user_id,start_at);
CREATE INDEX fitness_public_date ON fitness_sessions(visibility,status,start_at);
CREATE TABLE fitness_session_exercises (id TEXT PRIMARY KEY, session_id TEXT NOT NULL REFERENCES fitness_sessions(id) ON DELETE CASCADE, exercise_id TEXT NOT NULL REFERENCES exercise_library(id), position INTEGER NOT NULL);
CREATE INDEX session_exercises_parent ON fitness_session_exercises(session_id);
CREATE TABLE fitness_sets (id TEXT PRIMARY KEY, session_exercise_id TEXT NOT NULL REFERENCES fitness_session_exercises(id) ON DELETE CASCADE, position INTEGER NOT NULL, reps INTEGER CHECK(reps>0), weight REAL CHECK(weight>=0), duration REAL CHECK(duration>0), distance REAL CHECK(distance>0), rpe REAL CHECK(rpe>=1 AND rpe<=10), note TEXT NOT NULL DEFAULT '', completed INTEGER NOT NULL CHECK(completed IN(0,1)));
CREATE INDEX sets_parent ON fitness_sets(session_exercise_id);
CREATE TABLE workout_templates (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), name TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE workout_template_exercises (id TEXT PRIMARY KEY, template_id TEXT NOT NULL REFERENCES workout_templates(id) ON DELETE CASCADE, exercise_id TEXT NOT NULL REFERENCES exercise_library(id), position INTEGER NOT NULL);
CREATE INDEX template_exercises_parent ON workout_template_exercises(template_id);
CREATE TABLE workout_template_sets (id TEXT PRIMARY KEY, template_exercise_id TEXT NOT NULL REFERENCES workout_template_exercises(id) ON DELETE CASCADE, position INTEGER NOT NULL, reps INTEGER, weight REAL, duration REAL, distance REAL, rpe REAL, note TEXT NOT NULL DEFAULT '');
CREATE INDEX template_sets_parent ON workout_template_sets(template_exercise_id);

CREATE TABLE locations (id TEXT PRIMARY KEY, source_id INTEGER NOT NULL, kind TEXT NOT NULL CHECK(kind IN('country','region','city')), parent_id TEXT, country_code TEXT NOT NULL, country_name TEXT NOT NULL, country_name_zh TEXT NOT NULL DEFAULT '', region TEXT NOT NULL DEFAULT '', city TEXT NOT NULL DEFAULT '', name TEXT NOT NULL, name_zh TEXT NOT NULL DEFAULT '', latitude REAL, longitude REAL, search_name TEXT NOT NULL, source_commit TEXT NOT NULL);
CREATE INDEX location_search ON locations(search_name);
CREATE INDEX location_country ON locations(country_code,kind);
CREATE INDEX location_geo ON locations(latitude,longitude);
CREATE TABLE location_aliases (location_id TEXT NOT NULL REFERENCES locations(id), alias TEXT NOT NULL, PRIMARY KEY(alias,location_id));
CREATE TABLE travel_entries (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), location_id TEXT NOT NULL REFERENCES locations(id), start_date TEXT, end_date TEXT, description TEXT NOT NULL DEFAULT '', tags TEXT NOT NULL CHECK(json_valid(tags)), rating INTEGER CHECK(rating BETWEEN 1 AND 5), visibility TEXT NOT NULL DEFAULT 'private' CHECK(visibility IN('private','public')), deleted_at TEXT, updated_at TEXT NOT NULL, CHECK(end_date IS NULL OR (start_date IS NOT NULL AND end_date>=start_date)));
CREATE INDEX travel_owner_date ON travel_entries(user_id,start_date);
CREATE INDEX travel_public_date ON travel_entries(visibility,deleted_at,start_date);
CREATE TABLE travel_photos (id TEXT PRIMARY KEY, travel_id TEXT NOT NULL REFERENCES travel_entries(id) ON DELETE CASCADE, large_key TEXT NOT NULL UNIQUE, thumbnail_key TEXT NOT NULL UNIQUE, width INTEGER NOT NULL, height INTEGER NOT NULL, size INTEGER NOT NULL, position INTEGER NOT NULL);
CREATE INDEX travel_photos_parent ON travel_photos(travel_id);
CREATE TABLE travel_wishlist (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), location_id TEXT NOT NULL REFERENCES locations(id), visibility TEXT NOT NULL DEFAULT 'private' CHECK(visibility IN('private','public')), created_at TEXT NOT NULL, UNIQUE(user_id,location_id));
CREATE TABLE media_uploads (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), travel_id TEXT NOT NULL, large_key TEXT NOT NULL, thumbnail_key TEXT NOT NULL, width INTEGER NOT NULL, height INTEGER NOT NULL, size INTEGER NOT NULL, created_at INTEGER NOT NULL, attached INTEGER NOT NULL DEFAULT 0);
CREATE INDEX uploads_cleanup ON media_uploads(attached,created_at);
CREATE TABLE storage_cleanup_jobs (id TEXT PRIMARY KEY, object_key TEXT NOT NULL UNIQUE, attempts INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, last_error TEXT);
